import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(import.meta.dirname,'..');
const read = name => JSON.parse(fs.readFileSync(path.join(root,'content',name+'.json'),'utf8'));
const site=read('site'), plans=read('plans'), details=read('details');
const esc = v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const phone=site.phone.replace(/[^0-9+]/g,'');
const base=site.domain?site.domain.replace(/\/$/,'')+'/':'';
const links=site.details;
const assets=JSON.parse(fs.readFileSync(path.join(root,'assets/manifest.json'),'utf8'));
function dimensions(file){const a=Object.values(assets).find(x=>x.file===file);return a?` width="${a.width}" height="${a.height}"`:'';}
function img(file,alt,cls='',eager=false){return `<img src="${esc(file)}" alt="${esc(alt)}" class="${esc(cls)}"${dimensions(file)} ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;}
function figure(file,title,caption='',cls=''){return `<figure class="document ${cls}"><button type="button" class="zoom-image" data-image="${esc(file)}" data-caption="${esc(title)}" aria-label="${esc(title)} 확대">${img(file,title)}<span class="zoom-label">확대 보기 ＋</span></button>${caption?`<figcaption>${esc(caption)}</figcaption>`:''}</figure>`;}
function heading(k,title,text=''){return `<div class="section-head"><h2>${esc(title)}</h2></div>`;}
function link(key,text){return `<a class="text-link" href="${key}.html">${esc(text)} <span aria-hidden="true">↗</span></a>`;}
function overview(){return `<dl class="info-table">${site.overview.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;}
function premium(){return `<ol class="premium-list">${site.premium.map(p=>`<li>${img(p.image,p.title)}<div><h3>${esc(p.title)}</h3><p>${esc(p.text)}</p></div></li>`).join('')}</ol>`;}
function faq(){return `<div class="faq-list">${site.faq.map((p,i)=>`<details><summary><span class="item-number">${String(i+1).padStart(2,'0')}</span><span>${esc(p.q)}</span><span class="faq-sign" aria-hidden="true"></span></summary><div class="faq-answer"><p>${esc(p.a)}</p>${p.link?`<a class="source-link" href="${esc(p.link)}" target="_blank" rel="noopener noreferrer">${esc(p.linkLabel)} ↗</a>`:''}</div></details>`).join('')}</div>`;}
function contact(){return `<section class="contact-section" id="consultation"><div class="shell contact-grid"><div class="contact-copy"><h2>문의하기</h2><a class="contact-phone" data-placement="contact" href="tel:${phone}"><small>분양상담</small>${esc(site.phone)}</a></div><form id="lead-form" novalidate><h3>문의하기</h3><p class="form-help">문의 남겨주시면 담당자가 확인 후 순차적으로 연락 드리겠습니다.</p><div class="form-row"><label>이름 <span>*</span><input name="name" autocomplete="name" maxlength="30" required placeholder="이름을 입력해 주세요"></label><label>연락처 <span>*</span><input name="phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="20" required placeholder="010-0000-0000"></label></div>${site.contact.interestType?`<label>관심 타입<select name="interest_type"><option value="">선택 안 함</option>${plans.map(p=>`<option>${esc(p.block+' '+p.name)}</option>`).join('')}</select></label>`:''}${site.contact.visitDate?'<label>방문 희망일<input type="date" name="visit_date"></label>':''}<label>문의내용 <small>(선택)</small><textarea name="message" maxlength="1000" rows="3" placeholder="문의내용을 입력해 주세요"></textarea></label><div class="trap" aria-hidden="true"><label>웹사이트<input name="website" tabindex="-1" autocomplete="off"></label></div><details class="privacy"><summary>개인정보 수집·이용 안내</summary><p>수집·이용 목적: 분양 상담 및 방문 예약 안내<br>필수 항목: 이름, 연락처 / 선택 항목: 문의내용${site.contact.interestType?', 관심 타입':''}${site.contact.visitDate?', 방문 희망일':''}<br>보유·이용 기간: ${esc(site.contact.retention)}<br>동의를 거부할 수 있으며, 미동의 시 상담 신청이 제한됩니다.<br>개인정보 처리 및 삭제 문의: ${esc(site.contact.operator)} · ${esc(site.phone)} · ${esc(site.contact.email)}</p></details><label class="consent"><input name="privacy_agree" type="checkbox" required><span>개인정보 수집·이용에 동의합니다. <b>(필수)</b></span></label><button class="button submit" type="submit" ${site.contact.endpoint?'':'disabled'}>${site.contact.endpoint?esc(site.contact.cta):'온라인 접수 준비 중'} <span aria-hidden="true">→</span></button><p id="form-status" role="status" aria-live="polite"></p></form></div></section>`;}
function navCards(){return `<div class="more-grid">${links.map(d=>`<a class="more-card" href="${d.key}.html">${img(d.image,site.shortName+' '+d.title)}<div><h3>${esc(d.title)} <span aria-hidden="true">↗</span></h3></div></a>`).join('')}</div>`;}
function planCards(){return `<div class="filter-buttons" role="group" aria-label="전용면적별 평형 필터">${['전체','59','84','92'].map((f,i)=>`<button type="button" data-filter="${i?f:'all'}" aria-pressed="${!i}" class="${i?'':'active'}">${esc(f)}${i?'㎡':''}</button>`).join('')}</div><div class="plan-grid">${plans.filter(p=>!p.open).map(p=>`<a class="plan-card" href="plans.html#plan-${p.id}" data-family="${p.family}"><div class="plan-card-top"><h3>${esc(p.name)}<small>${esc(p.block)}</small></h3>${p.status?`<span class="badge">${esc(p.status)}</span>`:''}</div>${img(p.image,`${p.block} ${p.name} 타입 평면도`)}<div class="plan-card-bottom"><span>공급 <b>${p.count}실</b></span><span>상세 보기 ↗</span></div></a>`).join('')}</div>`;}
function planDetails(){return `<div class="plan-controls"><div class="block-buttons" role="group" aria-label="블록 선택">${['5BL','3BL','4BL'].map((b,i)=>`<button type="button" data-block="${b}" aria-pressed="${!i}">${b}</button>`).join('')}</div><div class="plan-tabs" role="tablist" aria-label="타입 선택">${plans.map((p,i)=>`<button type="button" role="tab" id="tab-${p.id}" aria-controls="plan-${p.id}" aria-selected="${!i}" tabindex="${i?-1:0}" data-plan="${p.id}" data-block-name="${p.block}">${esc(p.name)}</button>`).join('')}</div></div><div class="plan-panels">${plans.map(p=>`<section class="plan-panel" id="plan-${p.id}" role="tabpanel" aria-labelledby="tab-${p.id}"><div class="plan-detail-head"><div><span class="eyebrow">${esc(p.block)} · ${p.open?'오픈형':'일반형'}</span><h2>${esc(p.name)}</h2></div><dl><div><dt>전용면적 계열</dt><dd>${p.family}㎡</dd></div><div><dt>공급 규모</dt><dd>${p.count}실</dd></div><div><dt>블록</dt><dd>${p.block}</dd></div></dl></div>${figure(p.image,`${p.block} ${p.name} 평면도`,'참고용 이미지입니다.','plan-large')}<div class="plan-actions"><button type="button" class="button material-button zoom-image" data-image="${esc(p.sheet)}" data-caption="${esc(p.block+' '+p.name+' 면적·마감 안내')}" aria-label="${esc(p.name)} 면적·마감 자료 확대">면적 · 마감자료 보기 ＋</button><a class="button" data-cta="plan_consult" href="inquiry.html">이 타입 상담하기 ↗</a></div></section>`).join('')}</div>`;}
function table(s){return `<div class="table-scroll" tabindex="0" aria-label="${esc(s.title)} 표"><table><thead><tr>${s.headers.map(t=>`<th scope="col">${esc(t)}</th>`).join('')}</tr></thead><tbody>${s.rows.map(r=>`<tr>${r.map((t,i)=>`<${i?'td':'th scope="row"'}>${esc(t)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function detailSection(s,i){let body='';if(s.kind==='development')body=`<div class="development-layout">${figure(s.map,'별내 개발 위치도')}<div class="development-rail">${figure(s.rail,'별내역·GTX-B 계획 노선과 단지 입지지도')}<dl class="development-dates"><div><dt>GTX-B</dt><dd>${esc(s.gtx)}</dd></div><div><dt>스타필드 빌리지 별내</dt><dd>${esc(s.starfield)}</dd></div></dl></div></div>`;if(s.kind==='image')body=figure(s.image,s.title,s.caption);if(s.kind==='overview')body=overview();if(s.kind==='premium')body=premium();if(s.kind==='text')body=`<p class="body-copy">${esc(s.text)}</p>`;if(s.kind==='table')body=table(s);if(s.kind==='stats')body=`<div class="editorial-grid">${s.items.map(x=>`<article><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p>${x.link?`<a class="source-link" href="${esc(x.link)}" target="_blank" rel="noopener noreferrer">${esc(x.linkLabel)} ↗</a>`:''}</article>`).join('')}</div>`;if(s.kind==='gallery')body=`<div class="detail-gallery">${s.items.map(x=>figure(x.image,x.title,x.title)).join('')}</div>`;return `<section class="section shell ${s.kind==='text'?'text-section':''}">${heading('0'+(i+1),s.title,s.kind==='text'?'':s.text)}${body}</section>`;}
const modules={
 hero:()=>`<section class="hero hero-landscape" aria-labelledby="hero-title">${img(site.hero.image,site.name+' 수채화 조감도','hero-image',true)}<h1 id="hero-title" class="sr-only">${esc(site.hero.title)} · ${esc(site.hero.subtitle)}</h1></section>`,
 facts:()=>`<section class="facts-section" aria-label="단지 핵심정보"><dl class="shell facts">${site.facts.map(f=>`<div><dd>${esc(f.value)}<small>${esc(f.unit)}</small></dd><dt>${esc(f.label)}</dt></div>`).join('')}</dl></section>`,
 overview:()=>`<section class="section shell" id="overview"><div class="section-top">${heading('01 / OVERVIEW','별내자이 더 스타 이그제큐티브','별내 중심상업지역, 3개 블록 760실')}${link('overview','사업안내 전체 보기')}</div><div class="overview-grid">${figure('assets/overview.webp','별내자이 더 스타 3·4·5BL 조감도')}${overview()}</div></section>`,
 location:()=>`<section class="section tint" id="location"><div class="shell"><div class="section-top">${heading('02 / LOCATION','트리플 초역세권','별내역 8호선 · 경춘선 · GTX-B(계획)')}${link('location','입지환경 전체 보기')}</div><div class="location-grid">${figure('assets/location-map.webp','별내자이 더 스타 광역·생활권 입지지도','GTX-B 등 계획 노선과 예정 시설은 추진 상황에 따라 변경될 수 있습니다.')}<div class="location-copy">${site.location.map((l,i)=>`<article><h3>${esc(l.title)}</h3><p>${esc(l.text)}</p></article>`).join('')}</div></div></div></section>`,
 premium:()=>`<section class="section shell" id="premium"><div class="section-top">${heading('03 / PREMIUM','자이의 이름으로 더 빛나는 가치','지도전단의 PREMIUM 6')}${link('premium','프리미엄 전체 보기')}</div>${premium()}</section>`,
 plans:()=>`<section class="section plans-section" id="plans"><div class="shell"><div class="section-top">${heading('04 / UNIT PLAN','59 · 84 · 92㎡, 타입별 비교','일반 타입을 비교하고 상세에서 오픈형까지 확인할 수 있습니다.')}${link('plans','전체 21개 타입 보기')}</div>${planCards()}</div></section>`,
 terms:()=>`<section class="section shell" id="terms">${heading('CONTRACT',site.terms.title)}<dl class="info-table">${site.terms.items.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></section>`,
 more:()=>`<section class="section shell" id="more">${heading('MORE INFORMATION','더 자세히 알아보기')}${navCards()}</section>`,
 faq:()=>`<section class="section shell" id="faq">${heading('FAQ','자주 묻는 질문')}${faq()}</section>`,
 contact
};
function layout(key,title,description,body){const index=key==='index';const canonical=base?base+(index?'':key+'.html'):'';const ogImage=base?base+site.seo.image:site.seo.image;return `<!doctype html>
<html lang="ko"><head><meta charset="utf-8">${site.naverVerification?`<meta name="naver-site-verification" content="${esc(site.naverVerification)}">`:""}<meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${base?'index,follow,max-image-preview:large':'noindex,follow'}"><meta name="theme-color" content="${esc(site.brand.dark)}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:site_name" content="${esc(site.name)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(ogImage)}">${canonical?`<link rel="canonical" href="${esc(canonical)}"><meta property="og:url" content="${esc(canonical)}">`:''}<link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="master/styles.css"><style>:root{--brand:${site.brand.color};--navy:${site.brand.dark};--gold:${site.brand.accent}}</style><script src="runtime-config.js" defer></script><script src="master/app.js" defer></script></head>
<body id="top" data-page="${key}"><a class="skip" href="#main">본문 바로가기</a><header class="site-header"><div class="header-inner"><a class="brand" href="index.html" aria-label="${esc(site.name)} 홈">${img(site.brand.logo,'자이 로고','brand-logo',true)}<span><b>${esc(site.shortName)}</b><em>이그제큐티브</em></span></a><nav id="site-nav" aria-label="주요 메뉴">${links.map(d=>`<a href="${d.key}.html"${key===d.key?' aria-current="page"':''}>${esc(d.title==='단지·동호수 배치'?'단지안내':d.title)}</a>`).join('')}<a href="inquiry.html" data-cta="header_registration">문의하기</a></nav><a class="header-phone" href="tel:${phone}" data-placement="header">${esc(site.phone)}</a><button type="button" class="menu-toggle" aria-controls="site-nav" aria-expanded="false" aria-label="메뉴 열기"><span></span><span></span></button></div></header><main id="main">${body}</main><footer class="site-footer"><div class="shell"><div class="footer-top"><div class="footer-brand">${esc(site.shortName)}<small>이그제큐티브</small></div><a href="#top">맨 위로 ↑</a></div><p>${esc(site.name)} 분양상담 안내</p><p>홈페이지 관리자 ${esc(site.contact.operator)} · 대표번호 <a href="tel:${phone}">${esc(site.phone)}</a> · <a href="mailto:${esc(site.contact.email)}">${esc(site.contact.email)}</a></p><p>현장: 경기도 남양주시 별내동 1001 · 991 · 992</p><p class="footer-note">본 홈페이지는 분양상담 안내 페이지입니다. 이미지와 안내 내용은 실제 시공·운영 및 계약조건과 차이가 있을 수 있습니다. 계획·예정 항목은 변경될 수 있으며, 계약 전 해당 호실의 최신 계약 자료를 확인해야 합니다.</p><p class="copyright">© ${new Date().getFullYear()} ${esc(site.englishName)}</p></div></footer><div class="mobile-cta"><a href="tel:${phone}" data-placement="mobile_fixed">전화상담</a><a href="inquiry.html" data-cta="mobile_registration">문의하기 ↗</a></div><dialog id="lightbox" aria-labelledby="lightbox-caption"><div class="lightbox-toolbar"><p id="lightbox-caption"></p><div><button type="button" class="lightbox-size" aria-pressed="false">원본 크기</button><button type="button" class="lightbox-close" aria-label="확대 이미지 닫기">×</button></div></div><div class="lightbox-view"><img alt=""></div></dialog>${site.popup.enabled?`<dialog class="notice-popup" id="notice-popup" aria-labelledby="popup-title"><button type="button" class="popup-close" aria-label="안내 닫기">×</button><span class="eyebrow">NOTICE</span><h2 id="popup-title">${esc(site.popup.title)}</h2><p>${esc(site.popup.body)}</p><a class="button" data-cta="popup_consult" href="inquiry.html">${esc(site.popup.cta)}</a><button type="button" class="popup-today">오늘 하루 보지 않기</button></dialog>`:''}</body></html>`;}
const pages=[{key:'index',title:site.seo.title,description:site.seo.description,body:site.moduleOrder.filter(k=>site.modules[k]&&modules[k]).map(k=>modules[k]()).join('')}];
for(const d of links){const body=d.key==='plans'?`<section class="section shell plans-detail">${planDetails()}</section>`:(details[d.key]||[]).map(detailSection).join('');pages.push({key:d.key,title:`${site.name} ${d.title} | ${site.phone}`,description:`${site.name} ${d.subtitle}. ${site.seo.description}`,body:`<section class="page-heading shell"><div class="breadcrumb"><a href="index.html">홈</a><span>/</span>${esc(d.title)}</div><h1>${esc(d.title)}</h1></section>${body}`});}
pages.push({key:'inquiry',title:`${site.name} 문의하기 | ${site.phone}`,description:`${site.name} 분양 문의 ${site.phone}`,body:`<section class="page-heading shell"><h1>문의하기</h1></section>${contact()}`});
for(const p of pages)fs.writeFileSync(path.join(root,p.key+'.html'),layout(p.key,p.title,p.description,p.body));
fs.writeFileSync(path.join(root,'runtime-config.js'),'window.SITE_CONFIG = '+JSON.stringify({name:site.name,phone:site.phone,contact:site.contact,popup:site.popup,modules:site.modules})+';\n');
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${base?pages.map(p=>`<url><loc>${esc(base+(p.key==='index'?'':p.key+'.html'))}</loc></url>`).join(''):''}</urlset>\n`);
fs.writeFileSync(path.join(root,'robots.txt'),`User-agent: *\n${base?'Allow: /\nDisallow: /content/\nDisallow: /master/\nAllow: /master/styles.css\nAllow: /master/app.js\nDisallow: /backend/\nSitemap: '+base+'sitemap.xml':'Disallow: /'}\n`);
fs.writeFileSync(path.join(root,'assets/favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="'+site.brand.dark+'"/><text x="32" y="44" text-anchor="middle" fill="white" font-size="38" font-family="sans-serif">별</text></svg>');
console.log(`Built ${pages.length} static pages / ${plans.length} types. ${base?'Domain: '+base:'Preview mode: domain not set, noindex enabled.'}`);
